name: Spring Boot CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build Maven project
        run: mvn clean package -DskipTests

      - name: Build Docker image
        run: docker build -t springboot-app .

      # Optional: Push Docker image to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: anirudha123
          password: Anirudha@1203

      # - name: Push Docker image to Docker Hub
      #   run: |
      #     docker tag springboot-app <dockerhub-username>/springboot-app:latest
      #     docker push <dockerhub-username>/springboot-app:latest

      - name: Push Docker image to Docker Hub
        run: |
          docker tag springboot-app anirudha123/springboot-app:latest
          docker push anirudha123/springboot-app:latest
